{% set name = "plip" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d62c798b5ef6f3ae6ddd72e87c353bff8263e557dfa5f6ecf699cdf975f04ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plip = plip.plipcmd:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - lxml >=4.2.1
    - numpy >=1.13.3
    - openbabel >=3.0.0
    - python >=3.6
  run_constrained:
    - ImageMagick >=7.0
    - pymol-open-source >=2.3.0

test:
  imports:
    - plip
  commands:
    - plip --help

about:
  home: https://github.com/pharmai/plip
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Analyze non-covalent protein-ligand interactions in 3D structures
  description: |
    Protein-Ligand Interaction Profiler - Analyze and visualize non-covalent
    protein-ligand interactions in PDB files according to memo Salentin et al. (2015)
  doc_url: https://github.com/pharmai/plip/blob/master/DOCUMENTATION.md
  dev_url: https://github.com/pharmai/plip

extra:
  recipe-maintainers:
    - pharmai
    - hadim
    - mikemhenry
