{% set name = "plip" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce315d16df6f6c9f6924618b353221ea318072546f5f2d8b773b4a9923b7fc65

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plip = plip.plipcmd:main

requirements:
  host:
    - python
    - pip
  run:
    - lxml
    - numpy
    - openbabel
    - pymol
    - python

test:
  imports:
    - plip
  commands:
    - plip --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pharmai/plip
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Analyze non-covalent protein-ligand interactions in 3D structures
  description: |
    Protein-Ligand Interaction Profiler - Analyze and visualize non-covalent
    protein-ligand interactions in PDB files according to memo Salentin et al. (2015)
  doc_url: https://github.com/pharmai/plip/blob/master/DOCUMENTATION.md
  dev_url: https://github.com/pharmai/plip

extra:
  recipe-maintainers:
    - pharmai
    - hadim
