{% set name = "plip" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0998cfe3b7bded2c26e4e01492dcc3a6aa4f445936806be1634b2299353d9792

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plip = plip.plipcmd:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - lxml
    - numpy
    - openbabel
    - python >=3.6

test:
  imports:
    - plip
  commands:
    - plip --help

about:
  home: https://github.com/pharmai/plip
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Analyze non-covalent protein-ligand interactions in 3D structures
  description: |
    Protein-Ligand Interaction Profiler - Analyze and visualize non-covalent
    protein-ligand interactions in PDB files according to memo Salentin et al. (2015)
  doc_url: https://github.com/pharmai/plip/blob/master/DOCUMENTATION.md
  dev_url: https://github.com/pharmai/plip

extra:
  recipe-maintainers:
    - pharmai
    - hadim
